version: '3.8'

services:
  server:
    build: .
    container_name: app_finance_server
    restart: on-failure
    ports:
      - "${APP_PORT}:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    networks:
      - app_finance_network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:14
    container_name: app_finance_db
    restart: on-failure
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - app_finance_network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  app_finance_network:
    driver: bridge

volumes:
  postgres:
    driver: local